Add auto disappear functionality
canonical-web-and-design/cookie-policy pull request #5
Opened 2017-06-26 15:50 UTC by anthonydillon

## Done
Added self-destruct functionality to the notification.

## QA
- Run `gulp build`
- Open the index.html file
- Check the cookie policy self-destructs after 3 seconds
- Update the duration on in the index.html and refresh
- Check the duration matches your change
- Remove the duration and check it never goes away

## Details
Fixes https://github.com/canonical-webteam/cookie-policy/issues/3

2017-06-28 09:37 UTC, richmccartney requested changes

2017-06-28 09:37 UTC, richmccartney commented on src/js/cookie-policy.js
>          <div class="p-notification--cookie-policy">
As this is a popup and something that can be closed or hidden, I feel this should be using the ```<dialog>``` html element. Also add ```aria-labelledby``` or ```aria-describedby``` to give it more context and improve the accessibility.

2017-06-28 09:37 UTC, richmccartney commented on src/js/cookie-policy.js
>            <p class="p-notification__content">`;
The ```.js-close``` element should be a ```<button>``` element as we're not linking to a new page or anchor on the page.

2017-06-28 09:37 UTC, richmccartney commented on index.html
> +      'content': 'We use cookies to improve your experience. By your continued use of this site you accept such use.<br /> This notice will disappear by itself. To change your settings please <a href
Does the ```<a>``` tag need to explain it is going to an external page?

2017-06-28 16:44 UTC, anthonydillon commented
@richmccartney thanks for the review. Nice pointers, feeling much more tab friendly now. Please, could you have another look?

2017-06-29 10:23 UTC, richmccartney approved these changes

2017-06-29 10:23 UTC, richmccartney commented
🥇 a11y awesomeness, all LGTM and you can now merge this @anthonydillon

2017-06-29 10:25 UTC, merged